main: ink.anh.family.AnhyFamily
name: AnhyFamily
version: 0.1.0
author: AnhyDev
api-version: 1.13
depend: [AnhyLibAPI]
softdepend: [Vault]
description: AnhyFamily is a plugin for simulating family relationships on Minecraft servers
website: http://anh.ink/anhyfamily
commands:
    anhyfam:
        aliases: [anhyfamily, afam]
        usage: "[AnhyFamily] The command '/anhyfamily (/anhyfam, /afam)' execution error, please check the arguments' correctness.adoption"
    gender:
        aliases: [identity, gen]
        usage: "[AnhyFamily] The command '/gender (/identity, /gen)' execution error, please check the arguments' correctness."
    family:
        aliases: [fam]
        usage: "[AnhyFamily] The command '/family (/fam)' execution error, please check the arguments' correctness.adoption"
    marry:
        aliases: [married]
        usage: "[AnhyFamily] The command '/marry public player1 player2' or '/marry private player'"
    adoption:
        aliases: [adopt]
        usage: "[AnhyFamily] The command '/adoption (/adopt)' execution error, please check the arguments' correctness."
    fhome:
        aliases: [familyhome, fh]
        usage: "[AnhyFamily] The command '/fhome (/familyhome, fh)' execution error, please check the arguments' correctness."
    fchat:
        aliases: [familychat, fc]
        usage: "[AnhyFamily] The command '/fchat (/familychat, fc)' execution error, please check the arguments' correctness."
    fchest:
        aliases: [familychest, ft]
        usage: "[AnhyFamily] The command '/fchest (/familychest, /ft)' execution error, please check the arguments' correctness."
    fhugs:
        aliases: [familyhugs, hugs]
        usage: "[AnhyFamily] The command '/fhugs (/familyhugs, /hugs)' execution error, please check the arguments' correctness."