main: ink.anh.family.AnhyFamily
name: AnhyFamily
version: 0.1.0
author: AnhyDev
api-version: 1.13
depend: [AnhyLibAPI]
softdepend: [Vault]
description: AnhyFamily is a plugin for simulating family relationships on Minecraft servers
website: http://anh.ink/anhyfamily
commands:
    anhyfam:
        aliases: [anhyfamily]
        usage: "[AnhyFamily] The command '/anhyfamily (/anhyfam)' execution error, please check the arguments' correctness.adoption"
    gender:
        aliases: [identity]
        usage: "[AnhyFamily] The command '/gender (/identity)' execution error, please check the arguments' correctness."
    family:
        aliases: [fam]
        usage: "[AnhyFamily] The command '/family (/fam)' execution error, please check the arguments' correctness.adoption"
    adoption:
        aliases: [adopt]
        usage: "[AnhyFamily] The command '/adoption (/adopt)' execution error, please check the arguments' correctness."